# Generated by Django 4.1.7 on 2023-03-31 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='description of credit')),
                ('minimum_payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Minimum Payment')),
                ('maximum_payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Maximum Payment')),
                ('period', models.SmallIntegerField(verbose_name='credit period in months')),
                ('credit_type', models.CharField(choices=[('Automotive', 'natural'), ('Mortgages', 'Mortgages'), ('Commercial', 'Commercial')], max_length=100, verbose_name='Credit type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_credit', to='bank.bank')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_credit', to='client.client')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
